### ISSUE TITLE
Readme should ask to use commit hash when adding project as dependency.

### ISSUE THREAD

**Issue by AndrewKraevskii** [G3bE/raylib-zig#120]
When you adding project using instructions in README.md
```sh
zig fetch --save https://github.com/Not-Nik/raylib-zig/archive/devel.tar.gz
```
It downloads latest version and saves it's commit hash. Now every time raylib bindings updated user should update hash manually or else clean build without cache would fail. However build with cache will succeed. It makes so when someone new wants to clone and build repo what uses raylib they should change hash or devel to commit hash.

Instead README.md should advertise this usage:
```sh
zig fetch --save https://github.com/Not-Nik/raylib-zig/archive/<LATEST-COMMIT-HASH>.tar.gz
```

**Comment by Not-Nik** [comment]
This is not an option for several reasons:

 - I would like to have one single copyable line, instead of the user manually having to edit it for the latest commit
 - Updating the commit in the README isn't an option as it would always lack behind at least one commit
 - This command is only a recommendation. If you don't want the latest development updates, feel free to use a specific commit, or even a release tag
 - I think this is a good way of "notifying" users of new updates
