### ISSUE TITLE
Generated build.zig.zon does not consider zig version or branches

### ISSUE THREAD

**Issue by vapandris** [G3bE/raylib-zig#121]
The generated build.zig.zon will always contain the following link:
https://github.com/Not-Nik/raylib-zig/archive/devel.tar.gz

I would expect the branch zig-0.12 to generate the Project folder with:
https://github.com/Not-Nik/raylib-zig/archive/zig-0.12.tar.gz

Same goes for branch zig-0.11 and future branches.

Currently when you're not using the latest zig version, and try to generate the Project, it works, however building it does not, since first, it will complain about the hash, and after that it will have compile errors, since the raylib-zig is on a later  zig version.

**Comment by Not-Nik** [comment]
`zig-0.11` and `zig-0.12` are development branches, that since have been merge into `devel`. They don't represent the latest version of `raylib-zig` on those Zig versions and aren't meant for actual use. Feel free to manually specify the commit right before `zig-0.12` was merged to use the library with Zig 0.11 (6eeb304ff33a745081f6176bde61d5c558bd2abf), but be aware that it doesn't use the latest raylib (raylib's commit is pinned in `build.zig.zon`). Latest `devel` should still be backwards compatible with Zig 0.12. I really don't see a reason to use these old versions, though.

**Comment by vapandris** [comment]
Oh, I've been using them like tags :D
That might not be the intended way, but when I want a bit of stability I'd do that, and I guess nothing is stopping me from changing the build.zig.zon url from `devel` to the zig version I wish to use :D

Anyway, good job on raylib-zig, it is greatly useful
