### ISSUE TITLE
Disable feature enabled in config.h

### ISSUE THREAD

**Issue by adamws** [G3bE/raylib-zig#166]
Readme mentions [enabling/disabling features](https://github.com/Not-Nik/raylib-zig?tab=readme-ov-file#defining-feature-macros), but apparently this does not work when trying to disable something which is enabled in `config.h` already, for example: 

```zig
raylib_artifact.defineCMacro("SUPPORT_SCREEN_CAPTURE", "0");
```

will have no effect since `-Dxxx=y` compiler flag does not overwrite value included from header.
I think that build system must patch/overwrite config.h to turn features off (which I'm not even sure is possible right now)

Related https://github.com/raysan5/raylib/issues/4411

**Comment by Not-Nik** [comment]
I can't fix this on the binding side. I'm also just at the mercy of raylib's build script.

**Comment by adamws** [comment]
Perhaps you could make it clear in readme which now suggest otherwise

**Comment by presentfactory** [comment]
Note that raylib's build script now exposes a `config` field in its options which can be used to override the values in config.h (it essentially parses that file and turns them into command line options, using the defaults only when options are not specified by the user). Exposing that in this wrapper would be useful I think.
That said, raylib is as usual annoyingly designed because for various macro-controlled features it only checks if the macro is defined rather than its value, so if the default config defines a macro you cannot override it in a way to "undefine" it with the system they have set up. If they were using `#if` instead of `#ifdef` you'd be able to override its value to 0 which would work to disable the feature with the current system they have implemented, but alas that is not the case currently.

Also unfortunately Zig's compiler does not support the -U flag to undefine definitions like GCC does, so it cannot even be hacked that way. Just will have to wait for raylib to make a fix or something.

**Comment by Logickin-Lambda** [comment]
Just came across an issue of conflicting Raylib-zig with zaudio which I need the miniaudio features for some dsp stuff. Has anyone figured out how to disable a certain features in some sort?

Update:

For my case, seems like:

``` zig
const raylib_dep = b.dependency("raylib_zig", .{
    .raudio = false,
});
```

Could solve my issues. Since I am going to write my own audio backend with zaudio anyways, it is fine to loss all the raudio features from my end.
